test:cargo:
  script:
  - rustup show
  - rustup default nightly-2024-10-31
  #- wasm-pack --version
  #- wasm-pack build wasm-notebook --target web
  - cargo build --bin mech
  - cargo test --package mech-syntax