variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:cargo:
  script:
  - rustup show
  - rustup default nightly-2022-08-25
  - wasm-pack build wasm-notebook --target web
  - cargo build --bin mech --release
  - ./target/release/mech test tests
  - cd src/syntax
  - cargo test --release