test:cargo:
  script:
  - rustup show
  - rustup default nightly-2024-03-25
  - wasm-pack build wasm-notebook --target web
  - cargo build --bin mech --release
  - cargo test --package mech-syntax --release