variables:
  GIT_SUBMODULE_STRATEGY: recursive

image: "rust:latest"

test:cargo:
  script:
  - rustup default nightly-2021-02-22
  - rustup show
  - rustc --version && cargo --version
  - rustup component add rust-src
  - cargo build --bin mech --release
  - ./target/release/mech test tests
  - ./target/release/mech test https://gitlab.com/mech-lang/machines/math/-/raw/master/tests/math.mec
  - ./target/release/mech test https://gitlab.com/mech-lang/machines/stats/-/raw/master/tests/stats.mec

on-schedule:
  stage: build
  only:
    - schedules
  script:
    - git config user.email "${GITLAB_USER_EMAIL}"
    - git config user.name "${GITLAB_USER_NAME}"
    - git remote add api-origin https://oauth2:${GITLAB_ACCESS_TOKEN}@gitlab.com/${CI_PROJECT_PATH}
    - git tag -a "nightly-$(date +%Y-%m-%d)" -m "Auto-Release"
    - git push api-origin "nightly-$(date +%Y-%m-%d)"
