[package]
name = "mech"
version = "0.0.5"
authors = ["Corey Montella <corey@mech-lang.org>"]
description = "Main crate for the Mech programming language. Provides a REPL and hosted editor."
documentation = "http://docs.mech-lang.org"
homepage = "http://mech-lang.org"
repository = "https://github.com/mech-lang/mech"
keywords = ["mech", "language", "programming", "dataflow", "runtime"]
categories = ["science::robotics", "science", "game-engines", "web-programming"]
license = "Apache-2.0"
readme = "README.md"
edition = "2018"

[badges]
gitlab = { repository = "mech-lang/mech", branch = "main" }
maintenance = { status = "actively-developed" }

[dependencies]
<<<<<<< HEAD
mech-core = {git = "https://gitlab.com/mech-lang/core"}
mech-syntax = {git = "https://gitlab.com/mech-lang/syntax"}
mech-program = {git = "https://gitlab.com/mech-lang/program"}
mech-utilities = {git = "https://gitlab.com/mech-lang/utilities"}
=======
mech-core = {path = "core"}
mech-syntax = {path = "syntax"}
mech-program = {path = "program"}
mech-utilities = {path = "utilities"}
>>>>>>> ae5d7ba9820561c6e38e58a3d43a1441e884402b

clap = "2.34.0"
colored = "2.0.0"
nom = {path = "syntax/vendor/nom"}
reqwest = {version = "0.11.3", features = ["blocking"]}
bincode = "1.3.3"
serde = "1.0.133"
serde_derive = "1.0.133"
serde_json = "1.0.74"
crossbeam-channel = "0.5.1"
seahash = "4.1.0"
crossterm = "0.22.1"
lazy_static = "1.4.0"
tui = { version = "0.10", default-features = false, features = ['crossterm'] }
tokio = {version = "1.6.1", features = ["full"]}
warp = "0.3.2"
websocket = "0.26.2"
miniz_oxide = "0.5.1"
base64 = "0.13.0"
eframe = { version = "0.17.0" }
image = { version = "0.24.0", default-features = false, features = [
  "ico",
  "jpeg",
  "png",
] }
syntect = { version = "4", optional = true, default-features = false, features = [
  "default-fancy",
] }

[workspace]

members = [
  "notebook",
  "notebook2",
]

[profile.release]
debug = true

[build-dependencies]
winres = "0.1.12"

[package.metadata.winres]
OriginalFilename = "MECH.EXE"
LegalCopyright = "Copyright © 2022"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
tracing-wasm = "0.2"

[patch.'https://gitlab.com/mech-lang/core']
mech-core = { path = 'core' }

[patch.'https://gitlab.com/mech-lang/syntax']
mech-core = { path = 'syntax' }

[patch.'https://gitlab.com/mech-lang/program']
mech-core = { path = 'program' }

[patch.'https://gitlab.com/mech-lang/utilities']
mech-core = { path = 'utilities' }