[package]
name = "mech"
version = "0.0.5"
authors = ["Corey Montella <corey@mech-lang.org>"]
description = "Main crate for the Mech programming language. Provides a REPL and hosted editor."
documentation = "http://docs.mech-lang.org"
homepage = "http://mech-lang.org"
repository = "https://github.com/mech-lang/mech"
keywords = ["mech", "language", "programming", "dataflow", "runtime"]
categories = ["science::robotics", "science", "game-engines", "web-programming"]
license = "Apache-2.0"
readme = "README.md"
edition = "2018"

[badges]
gitlab = { repository = "mech-lang/mech", branch = "main" }
maintenance = { status = "actively-developed" }

[dependencies]
mech-core = {git = "https://gitlab.com/mech-lang/core"}
mech-syntax = {git = "https://gitlab.com/mech-lang/syntax"}
mech-program = {git = "https://gitlab.com/mech-lang/program"}
mech-utilities = {git = "https://gitlab.com/mech-lang/utilities"}

clap = "2.33.3"
colored = "2.0.0"
nom = "5.1.1"
reqwest = {version = "0.11.3", features = ["blocking"]}
bincode = "1.3.1"
serde = "1.0.123"
serde_derive = "1.0.123"
serde_json = "1.0.62"
crossbeam-channel = "0.4.0"
seahash = "4.1.0"
crossterm = "0.17"
lazy_static = "1.4.0"
tui = { version = "0.10", default-features = false, features = ['crossterm'] }
tokio = {version = "1.6.1", features = ["full"]}
warp = "0.3"
websocket = "0.26.2"

[workspace]

members = [
  "notebook",
]

[profile.release]
debug = true