[package]
name = "mech"
version = "0.2.17"
authors = ["Corey Montella <corey@mech-lang.org>"]
description = "Mech is a reactive programming language for building robots, games, and animations."
documentation = "https://mech-lang.org/docs"
homepage = "https://mech-lang.org"
repository = "https://github.com/mech-lang/mech"
keywords = ["mech", "language", "programming", "dataflow", "runtime"]
categories = ["science::robotics", "science", "game-engines", "web-programming"]
license = "Apache-2.0"
readme = "README.md"
edition = "2021"
rust-version = "1.80"

[badges]
gitlab = { repository = "mech-lang/mech", branch = "main" }
maintenance = { status = "actively-developed" }

[dependencies]
mech-core = "0.2.17"
mech-syntax = "0.2.17"
#mech-program = "0.2.2"
#mech-utilities = "0.2.2"

clap = {version = "4.5.20", features = ["cargo"]}
colored = "2.1.0"
#nom = "7.1.3"
#hashbrown = "0.15.0"
#reqwest = {version = "0.12.4", features = ["blocking"]}
bincode = "1.3.3"
serde = "1.0.213"
serde_derive = "1.0.213"
serde_json = "1.0.128"
crossbeam-channel = "0.5.13"
#seahash = "4.1.0"
crossterm = "0.28.1"
lazy_static = "1.5.0"
#tui = { version = "0.19.0", default-features = false, features = ['crossterm'] }
#warp = "0.3.7"
#websocket = "0.27.1"
#miniz_oxide = "0.7.3"
#base64 = "0.22.1"
tabled = "0.16.0"

[workspace]

members = [
  "src/core",
  "src/syntax",
  "src/program",
  "src/utilities",
  "src/wasm",
  "wasm-notebook"
]

[build-dependencies]
winres = "0.1.12"

[package.metadata.winres]
OriginalFilename = "MECH.EXE"
LegalCopyright = "Copyright © 2024"

[patch.crates-io]
mech-core = { path = 'src/core' }
mech-syntax = { path = 'src/syntax'}
mech-program = { path = 'src/program'}
mech-utilities = { path = 'src/utilities'}
mech-wasm = { path = 'src/wasm'}

[patch.'https://gitlab.com/mech-lang/core']
mech-core = { path = 'src/core', version = '0.2.17' }

[patch.'https://gitlab.com/mech-lang/syntax']
mech-syntax = { path = 'src/syntax', version = '0.2.17' }