[package]
name = "mech"
version = "0.0.4"
authors = ["Corey Montella <corey@mech-lang.org>"]
description = "Main crate for the Mech programming language. Provides a REPL and hosted editor."
documentation = "http://docs.mech-lang.org"
homepage = "http://mech-lang.org"
repository = "https://github.com/mech-lang/mech"
keywords = ["mech", "language", "programming", "dataflow", "runtime"]
categories = ["science::robotics", "science", "game-engines", "web-programming"]
license = "Apache-2.0"
readme = "README.md"
edition = "2018"

[badges]
gitlab = { repository = "mech-lang/mech", branch = "master" }
maintenance = { status = "actively-developed" }

[dependencies]
mech-core = {git = "https://gitlab.com/mech-lang/core"}
mech-syntax = {git = "https://gitlab.com/mech-lang/syntax"}
mech-program = {git = "https://gitlab.com/mech-lang/program"}
mech-utilities = {git = "https://gitlab.com/mech-lang/utilities"}

clap = "2.33.0"
colored = "1.9.3"
nom = "5.1.1"
reqwest = "0.10.4"
bincode = "1.2.1"
serde = "1.0.106"
serde_derive = "1.0.106"
serde_json = "1.0.51"
actix = "0.9.0"
actix-web = "2.0.0"
actix-rt = "1.0.0"
actix-session = "0.3.0"
actix-files = "0.2.1"
actix-web-actors = "2.0.0"
tokio = { version = "0.2", features = ["macros"] }
crossbeam-channel = "0.4"
ahash = { version = "0.3.2", default-features = false}