[package]
name = "mech"
version = "0.2.0"
authors = ["Corey Montella <corey@mech-lang.org>"]
description = "Toolchain for the Mech programming language."
documentation = "http://docs.mech-lang.org"
homepage = "https://mech-lang.org"
repository = "https://github.com/mech-lang/mech"
keywords = ["mech", "language", "programming", "dataflow", "runtime"]
categories = ["science::robotics", "science", "game-engines", "web-programming"]
license = "Apache-2.0"
readme = "README.md"
edition = "2021"
rust-version = "1.74"

[badges]
gitlab = { repository = "mech-lang/mech", branch = "main" }
maintenance = { status = "actively-developed" }

[dependencies]
mech-core = {path = "src/core" }
mech-syntax = {path = "src/syntax", features = ["lang-server"]}
mech-program = {path = "src/program"}
mech-utilities = {path = "src/utilities"}

clap = "2.34.0"
colored = "2.0.4"
nom = "7.1.3"
hashbrown = "0.14.1"
reqwest = {version = "0.11.11", features = ["blocking"]}
bincode = "1.3.3"
serde = "1.0.189"
serde_derive = "1.0.189"
serde_json = "1.0.107"
crossbeam-channel = "0.5.8"
seahash = "4.1.0"
crossterm = "0.27.0"
lazy_static = "1.4.0"
tui = { version = "0.19.0", default-features = false, features = ['crossterm'] }
tokio = {version = "1.36.0", features = ["full"]}
warp = "0.3.6"
websocket = "0.26.5"
miniz_oxide = "0.7.1"
base64 = "0.21.4"

[workspace]

members = [
  "src/core",
  "src/syntax",
  "src/program",
  "src/utilities",
  "src/wasm",
  "wasm-notebook"
]

[build-dependencies]
winres = "0.1.12"

[package.metadata.winres]
OriginalFilename = "MECH.EXE"
LegalCopyright = "Copyright © 2023"

[patch.crates-io]
mech-core = { path = 'src/core', version = '0.2' }
mech-syntax = { path = 'src/syntax', version = '0.2' }
mech-program = { path = 'src/program', version = '0.2' }
mech-utilities = { path = 'src/utilities', version = '0.2' }
mech-wasm = { path = 'src/wasm', version = '0.2' }

[patch.'https://gitlab.com/mech-lang/core']
mech-core = { path = 'src/core', version = '0.2' }

[patch.'https://gitlab.com/mech-lang/syntax']
mech-syntax = { path = 'src/syntax', version = '0.2' }

[patch.'https://gitlab.com/mech-lang/program']
mech-program = { path = 'src/program', version = '0.2' }

[patch.'https://gitlab.com/mech-lang/utilities']
mech-utilities = { path = 'src/utilities', version = '0.2' }

[patch.'https://gitlab.com/mech-lang/wasm']
mech-wasm = { path = 'src/wasm', version = '0.2' }