[package]
name = "mech"
version = "0.0.5"
authors = ["Corey Montella <corey@mech-lang.org>"]
description = "Main crate for the Mech programming language. Provides a REPL and hosted editor."
documentation = "http://docs.mech-lang.org"
homepage = "http://mech-lang.org"
repository = "https://github.com/mech-lang/mech"
keywords = ["mech", "language", "programming", "dataflow", "runtime"]
categories = ["science::robotics", "science", "game-engines", "web-programming"]
license = "Apache-2.0"
readme = "README.md"
edition = "2018"

[badges]
gitlab = { repository = "mech-lang/mech", branch = "main" }
maintenance = { status = "actively-developed" }

[dependencies]
mech-core = {path = "../core"}
mech-syntax = {path = "../syntax"}
mech-program = {path = "../program"}
mech-utilities = {path = "../utilities"}

clap = "2.34.0"
colored = "2.0.0"
nom = "6.2.1"
reqwest = {version = "0.11.3", features = ["blocking"]}
bincode = "1.3.3"
serde = "1.0.133"
serde_derive = "1.0.133"
serde_json = "1.0.74"
crossbeam-channel = "0.5.1"
seahash = "4.1.0"
crossterm = "0.22.1"
lazy_static = "1.4.0"
tui = { version = "0.10", default-features = false, features = ['crossterm'] }
tokio = {version = "1.6.1", features = ["full"]}
warp = "0.3.2"
websocket = "0.26.2"
miniz_oxide = "0.5.1"
base64 = "0.13.0"

[workspace]

members = [
  "notebook",
]

[profile.release]
debug = true
