[package]
name = "mech"
version = "0.0.4"
authors = ["Corey Montella <corey@mech-lang.org>"]
description = "Main crate for the Mech programming language. Provides a REPL and hosted editor."
documentation = "http://docs.mech-lang.org"
homepage = "http://mech-lang.org"
repository = "https://github.com/mech-lang/mech"
keywords = ["mech", "language", "programming", "dataflow", "runtime"]
categories = ["science::robotics", "science", "game-engines", "web-programming"]
license = "Apache-2.0"
readme = "README.md"
edition = "2018"

[badges]
gitlab = { repository = "mech-lang/mech", branch = "master" }
maintenance = { status = "actively-developed" }

[dependencies]
mech-core = {path = "../core"}
mech-syntax = {path = "../syntax"}
mech-server = {path = "../server"}
mech-program = {path = "../program"}
mech-utilities = {path = "../utilities"}

clap = "2.33.0"
term-painter = "0.2.4"
colored = "1.9.3"
nom = "5.1.1"
reqwest = "0.9.22"
bincode = "1.2.1"
serde = "1.0.106"
serde_derive = "1.0.106"
serde_json = "1.0.51"