[package]
name = "mech"
version = "0.0.1"
authors = ["Corey Montella <corey@mechlang.net>"]

[dependencies]
mech-core = {path = "core"}
mech-syntax = {path = "syntax"}
mech-server = {path = "server"}
clap = "2.31.2"
term-painter = "0.2.4"