[package]
name = "mech-core"
version = "0.2.11"
authors = ["Corey Montella <corey@mech-lang.org>"]
description = "The Mech language runtime."
documentation = "http://docs.mech-lang.org"
homepage = "https://mech-lang.org"
repository = "https://github.com/mech-lang/mech"
keywords = ["mech", "language", "programming", "dataflow", "runtime"]
categories = ["no-std", "science::robotics", "science", "game-engines", "database-implementations"]
license = "Apache-2.0"
readme = "README.md"
edition = "2021"

[badges]
gitlab = { repository = "mech-lang/core", branch = "main" }
maintenance = { status = "actively-developed" }

[features]
default = ["stdlib", "parallel"]
stdlib = ["time"]
parallel = ["rayon"]
no-std = ["rlibc"]
wasm = ["web-sys", "wasm-bindgen"]

[dependencies]
hashbrown = "0.14.5"
serde = {version = "1.0.210", default-features = false, features = ["alloc"] }
serde_derive = "1.0.210"
rlibc = { version = "=1.0", optional = true }
lazy_static = "1.5.0"
seahash = "4.1.0"
indexmap = "2.5.0"
rayon = {version = "1.10.0", optional = true}
time = {version = "0.3.36", optional = true}
ed25519-dalek = {version = "2.1.1", default-features = false, features = ["rand_core"]}
getrandom = { version = "0.2.15", features = ["js"]}
rand = {version = "0.8.5"}
tinyrand = "0.5.0"
rand_core = {version = "0.6.4"}
wasm-bindgen = {version = "0.2.93", optional = true}
nalgebra = "0.33.0"
simba = "0.9.0"
libm = "0.2.8"
tabled = "0.16.0"
paste = "1.0.15"

[dependencies.web-sys]
version = "0.3.70"
features = [
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',
  'Crypto',
  'console'
]
optional = true

[dependencies.num-traits]
version = "0.2.19"
default-features = false
features = ["libm"]