[package]
name = "mech-core"
version = "0.2.0"
authors = ["Corey Montella <corey@mech-lang.org>"]
description = "The Mech language runtime. It's a small dataflow engine that accepts transactions of changes, and applies them to a compute network."
documentation = "http://docs.mech-lang.org"
homepage = "https://mech-lang.org"
repository = "https://github.com/mech-lang/core"
keywords = ["mech", "language", "programming", "dataflow", "runtime"]
categories = ["no-std", "science::robotics", "science", "game-engines", "database-implementations"]
license = "Apache-2.0"
readme = "README.md"
edition = "2021"

[badges]
gitlab = { repository = "mech-lang/core", branch = "main" }
maintenance = { status = "actively-developed" }

[features]
default = ["stdlib", "parallel"]
stdlib = ["time"]
parallel = ["rayon"]
no-std = ["rlibc"]
crypto = ["rand", "rand_core", "ed25519-dalek", "getrandom",]
wasm = ["crypto", "web-sys", "wasm-bindgen"]

[dependencies]
hashbrown = "0.14.1"
serde = {version = "1.0.189", default-features = false, features = ["alloc"] }
serde_derive = "1.0.189"
rlibc = { version = "=1.0", optional = true }
lazy_static = "1.4.0"
seahash = "4.1.0"
indexmap = "2.0.2"
rayon = {version = "1.8.0", optional = true}
time = {version = "0.3.30", optional = true}
ed25519-dalek = {version = "2.0.0", optional = true, default-features = false, features = ["rand_core"]}
getrandom = { version = "0.2.10", features = ["js"], optional = true}
rand = {version = "0.8.5", optional = true}
rand_core = {version = "0.6.4", optional = true}
wasm-bindgen = {version = "0.2.87", optional = true}

[dependencies.web-sys]
version = "0.3.64"
features = [
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',
  'Crypto',
  'console'
]
optional = true

[dependencies.num-traits]
version = "0.2.17"
default-features = false
features = ["libm"]