[package]
name = "mech-syntax"
version = "0.2.0"
authors = ["Corey Montella <corey@mech-lang.org>"]
description = "A toolchain for compiling textual syntax into Mech blocks."
documentation = "http://docs.mech-lang.org"
homepage = "https://mech-lang.org"
repository = "https://github.com/mech-lang/syntax"
keywords = ["mech", "language", "programming", "parser", "compiler"]
categories = ["no-std", "science::robotics", "science", "parser-implementations"]
license = "Apache-2.0"
readme = "README.md"
edition = "2021"

[badges]
gitlab = { repository = "mech-lang/syntax", branch = "main" }
maintenance = { status = "actively-developed" }

[features]
default = []
no-std = ["mech-core/no-std", "rlibc"]
lang-server = ["tower-lsp", "tokio"]

[dependencies]
mech-core = {path = "../core"}

hashbrown = "0.14.5"
lazy_static = "1.4.0"
nom = "7.1.3"
nom-unicode = "0.3.0"
unicode-segmentation = "1.11.0"
rlibc = { version = "=1.0", optional = true }
serde = "1.0.189"
serde_derive = "1.0.203"
colored = "2.1.0"
nalgebra = "0.33.0"
indexmap = "2.2.6"
tabled = "0.15.0"
libm = "0.2.8"

tower-lsp = {version = "0.20.0", optional = true}
tokio = { version = "1.37.0", features = ["full"], optional = true }

[profile.release]
debug = true