name: Build and Release Binaries

on:
  push:
    tags:
      - 'v*'  # Trigger workflow on version tags like 'v1.0', 'v2.0.1', etc.

jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build project
        run: cargo build --release

      - name: Upload Linux binaries
        uses: actions/upload-artifact@v3
        with:
          name: linux-binaries
          path: target/release/

  build-windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build project
        run: cargo build --release

      - name: Upload Windows binaries
        uses: actions/upload-artifact@v3
        with:
          name: windows-binaries
          path: target/release/

  build-macos:
    name: Build for macOS
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build project
        run: cargo build --release

      - name: Upload macOS binaries
        uses: actions/upload-artifact@v3
        with:
          name: macos-binaries
          path: target/release/
