name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
    - name: Setup
      run: rustup default nightly-2022-03-27
    - name: Build
      run: cargo build --bin mech --release
    - name: Run tests
      run: |
        ./target/release/mech test tests
