name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Setup
      run: rustup default nightly-2024-05-26
    - name: Build
      run: wasm-pack --version
      run: wasm-pack build wasm-notebook --target web
      run: cargo build --bin mech --release
    - name: Run tests
      run: cargo test --package mech-syntax --release
