name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: rustup default nightly-2021-02-22
    - name: Build
      run: cargo build --bun mech --release
    - name: Run tests
      run: ./target/release/mech test tests
