name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: rustup default nightly-2021-02-22
    - name: Build
      run: cargo build --bin mech --release
    - name: Run tests
      run: |
        ./target/release/mech test tests
        ./target/release/mech test https://gitlab.com/mech-lang/machines/math/-/raw/main/tests/math.mec
        ./target/release/mech test https://gitlab.com/mech-lang/machines/stats/-/raw/main/tests/stats.mec
